### ISSUE TITLE
Having a hard time with jekyll

### ISSUE THREAD

**Issue by dagerebe** [dagerebe/portfolio#17]
Hey Thomas,
I have been trying to avoid messaging you over this hard time. But I have come to the point where I am really confused and kinda frustrated that I just cannot understand Jekyll. My site just is not working and I do not know why. 

On my home page I was hoping that all the css would stay in place but my corners that should be on all the images arn't working.

Also for some reason my work page wont work. I can't get my md file to link...

It is a big mess and I don't know if you can help me figure out what is wrong because I feel like I am missing alot of info. 

Sorry to bother you. I just don't want to lose both weeks worth of marks...
Thanks,
Rebecca

@thomasjbradley

**Comment by thomasjbradley** [comment]
_Re: corners_

Here, in the HTML:
https://github.com/dagerebe/portfolio/blob/gh-pages/index.html#L16-L25

The loop exists inside the `.image` class, meaning all the images will be inside one thing with the corner on it. I think that all those classes on the `<ul>` tag need to be moved down to the `<li>` tag instead.

---

_Re: work page_

If I understand what you're trying to do... then this line here:
https://github.com/dagerebe/portfolio/blob/gh-pages/work.html#L9
Should be `{% for work in site.data.preview %}` and it should be getting everything from the data file.

As it's set up right now, Jekyll can't pull information from another file without it being data or an include. So the `portwork` can't be pulled into the work page.
